begin;

create table if not exists private.review_share_links (
  id uuid primary key default gen_random_uuid(),
  token_hash bytea not null unique,
  project_key text not null,
  version_key text not null,
  passcode_hash text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  use_count integer not null default 0,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint review_share_project_key_length check (char_length(project_key) between 1 and 128),
  constraint review_share_version_key_length check (char_length(version_key) between 1 and 32),
  constraint review_share_failed_attempts_nonnegative check (failed_attempts >= 0),
  constraint review_share_use_count_nonnegative check (use_count >= 0)
);

create index if not exists idx_review_share_links_expires_at
  on private.review_share_links (expires_at);

create table if not exists private.review_share_creation_attempts (
  id bigint generated by default as identity primary key,
  requester_ip text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_review_share_creation_attempts_ip_created
  on private.review_share_creation_attempts (requester_ip, created_at desc);

create or replace function public.create_review_share_access(
  p_project_key text,
  p_version_key text,
  p_passcode text,
  p_ttl_days integer default 7
)
returns table(token text, expires_at timestamptz)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  generated_token text;
  request_ip text;
  request_count integer;
  link_expiry timestamptz;
begin
  if p_project_key is null or char_length(p_project_key) not between 1 and 128 then
    raise exception 'invalid project key';
  end if;
  if p_version_key is null or char_length(p_version_key) not between 1 and 32 then
    raise exception 'invalid version key';
  end if;
  if p_passcode is null or p_passcode !~ '^[0-9]{6}$' then
    raise exception 'passcode must contain exactly 6 digits';
  end if;
  if p_ttl_days is null or p_ttl_days not between 1 and 30 then
    raise exception 'ttl must be between 1 and 30 days';
  end if;

  request_ip := split_part(
    coalesce(
      current_setting('request.headers', true)::jsonb ->> 'x-forwarded-for',
      'unknown'
    ),
    ',',
    1
  );

  delete from private.review_share_creation_attempts
  where created_at < now() - interval '24 hours';

  select count(*)
  into request_count
  from private.review_share_creation_attempts
  where requester_ip = request_ip
    and created_at >= now() - interval '1 hour';

  if request_count >= 20 then
    raise exception 'share link rate limit exceeded';
  end if;

  insert into private.review_share_creation_attempts (requester_ip)
  values (request_ip);

  generated_token := encode(extensions.gen_random_bytes(24), 'hex');
  link_expiry := now() + make_interval(days => p_ttl_days);

  insert into private.review_share_links (
    token_hash,
    project_key,
    version_key,
    passcode_hash,
    expires_at
  )
  values (
    extensions.digest(generated_token, 'sha256'),
    p_project_key,
    p_version_key,
    extensions.crypt(p_passcode, extensions.gen_salt('bf', 10)),
    link_expiry
  );

  return query select generated_token, link_expiry;
end;
$$;

create or replace function public.validate_review_share_access(
  p_token text,
  p_project_key text,
  p_version_key text,
  p_passcode text
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  link private.review_share_links%rowtype;
  next_failed_attempts integer;
begin
  if p_token is null or char_length(p_token) <> 48
    or p_project_key is null or p_version_key is null
    or p_passcode is null or p_passcode !~ '^[0-9]{6}$' then
    return false;
  end if;

  select *
  into link
  from private.review_share_links
  where token_hash = extensions.digest(p_token, 'sha256')
    and project_key = p_project_key
    and version_key = p_version_key
    and revoked_at is null
    and expires_at > now()
  for update;

  if not found or (link.locked_until is not null and link.locked_until > now()) then
    return false;
  end if;

  if link.passcode_hash = extensions.crypt(p_passcode, link.passcode_hash) then
    update private.review_share_links
    set failed_attempts = 0,
        locked_until = null,
        use_count = use_count + 1,
        last_used_at = now()
    where id = link.id;
    return true;
  end if;

  next_failed_attempts := link.failed_attempts + 1;
  update private.review_share_links
  set failed_attempts = next_failed_attempts,
      locked_until = case
        when next_failed_attempts >= 10 then now() + interval '15 minutes'
        else null
      end
  where id = link.id;

  return false;
end;
$$;

revoke all on function public.create_review_share_access(text, text, text, integer)
  from public, anon, authenticated;
revoke all on function public.validate_review_share_access(text, text, text, text)
  from public, anon, authenticated;

-- Temporary bridge until Supabase Auth replaces the local demo accounts.
-- Both functions validate inputs and expose no table rows. Creation is also
-- rate-limited per request IP. Restrict creation to authenticated after Auth cutover.
grant execute on function public.create_review_share_access(text, text, text, integer)
  to anon, authenticated;
grant execute on function public.validate_review_share_access(text, text, text, text)
  to anon, authenticated;

commit;
